name: Build and package full application

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read
    attestations: write

jobs:
    dotnet_build_matrix:
        strategy:
            matrix:
                arch: [x64, ARM64, any]
            fail-fast: false
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: true
            - name: Install mono
              working-directory: ./.github_build
              run: sh mono_install.sh
            - name: Build application
              working-directory: ./.github_build
              run: python3 build.py ${{ matrix.arch }}
            - name: Debug
              run: |
                  echo "pwd: $(pwd)"
                  echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
                  ARTIFACT_FOLDER="${{ github.workspace }}/.github_build/.build"
                  ls -laR "$ARTIFACT_FOLDER" || echo "'$ARTIFACT_FOLDER' does not exist or is empty."
              continue-on-error: true
            - name: Generate artifact attestation
              uses: actions/attest-build-provenance@v2
              with:
                  subject-path: |
                      ./.github_build/.build/*.exe
                      ./.github_build/.build/ui.dll
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dotnet-${{ matrix.arch }}
                  path: ./.github_build/.build
                  include-hidden-files: true
    final_matrix:
        needs:
            - dotnet_build_matrix
        strategy:
            matrix:
                os: [windows, macos, linux]
                arch: [x86_64, aarch64]
                include:
                    - arch: x86_64
                      dotnet_arch: x64
                    - arch: aarch64
                      dotnet_arch: ARM64
                    - os: macos
                      dotnet_arch: any
                    - os: linux
                      dotnet_arch: any
            fail-fast: false
        runs-on: ubuntu-latest
        steps:
            - name: Download dotnet artifact
              uses: actions/download-artifact@v4
              with:
                  name: dotnet-${{ matrix.dotnet_arch }}
            - name: Generate artifact attestation
              uses: actions/attest-build-provenance@v2
              with:
                  subject-path: ./*
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: full-${{matrix.os}}-${{matrix.arch}}-dotnet_${{matrix.dotnet_arch}}
                  path: ./
                  include-hidden-files: true